kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: keycloak-public-tls
  namespace: sso-noprod
  labels:
    app: keycloak
spec:
  host: sso-noprod.cclh.io
  # path: /hola
  to:
    kind: Service
    name: keycloak
    weight: 100
  port:
    targetPort: keycloak
  tls:
    termination: reencrypt
    certificate: placeholder
    key: |-
      placeholder
    caCertificate: |-
      placeholder
  wildcardPolicy: None
  
