apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- operator/rhsso-operator_resourcegroups.yaml
- operator/rhsso-operator.yaml

- instance/secret-externaldb.yaml
- instance/secret-sso-credential.yaml
- instance/sso-instance.yaml
