apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- namespace.yaml

- instance/secret-externaldb.yaml
- instance/secret-sso-credential.yaml
- instance/sso-instance.yaml

- definitions/test-client-testclient.yaml
- definitions/test-realm.yaml


patches:
- patch: |-
    - op: add
      path: /spec/targetNamespaces/-
      value: rhsso-dev
  target:
    group: operators.coreos.com
    kind: OperatorGroup
    name: rhsso
    version: v1
