apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: sso
  name: keycloak
spec:
  extensions:
    - >-
      https://raw.githubusercontent.com/mcaballol/ssothemetest/main/example-theme-0.0.1-SNAPSHOT.jar
  externalAccess:
    enabled: true
  externalDatabase:
    enabled: true
  instances: 1
  keycloakDeploymentSpec:
    imagePullPolicy: Always
  postgresDeploymentSpec:
    imagePullPolicy: Always