---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  generation: 1
  name: rhsso-dev
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: rhsso-dev
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: rhsso-dev
    server: 'https://kubernetes.default.svc'
  source:
    path: overlays/dev
# we specify the folder for the files
    repoURL: 'https://github.com/mcaballol/gitops-deploy-sso.git'
# the repository url
    targetRevision: main
# and branch, in this case HEAD / main 
  project: rhsso-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    retry:
      limit: 10
    managedNamespaceMetadata:
      annotations:
        argocd.argoproj.io/sync-wave: "0"
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:
    - CreateNamespace=true