kind: KeycloakClient
apiVersion: keycloak.org/v1alpha1
metadata:
  name: 3scale-oidc02
  labels:
    app: sso
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  realmSelector:
    matchLabels:
      app: sso-test
  client:
    clientId: 3scale-oidc02
    secret: 3scale-oidc02
    clientAuthenticatorType: client-secret
    consentRequired: false
    standardFlowEnabled: false
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: true
    protocolMappers:
      - name: Client IP Address
        protocol: openid-connect
        protocolMapper: oidc-usersessionmodel-note-mapper
        consentRequired: false
        config:
          user.session.note: clientAddress
          id.token.claim: 'true'
          access.token.claim: 'true'
          claim.name: clientAddress
          jsonType.label: String
      - name: Client ID
        protocol: openid-connect
        protocolMapper: oidc-usersessionmodel-note-mapper
        consentRequired: false
        config:
          user.session.note: clientId
          id.token.claim: 'true'
          access.token.claim: 'true'
          claim.name: clientId
          jsonType.label: String
      - name: Client Host
        protocol: openid-connect
        protocolMapper: oidc-usersessionmodel-note-mapper
        consentRequired: false
        config:
          user.session.note: clientHost
          id.token.claim: 'true'
          access.token.claim: 'true'
          claim.name: clientHost
          jsonType.label: String     
    defaultClientScopes: 
      - "web-origins"
      - "acr"
      - "profile"
      - "roles"
      - "email"
      
    optionalClientScopes: 
      - "address"
      - "phone"
      - "offline_access"
      - "microprofile-jwt"
    
    access:
      view: true
      configure: true
      manage: true
    
    attributes:
      saml.force.post.binding: 'false'
      saml.multivalued.roles: 'false'
      frontchannel.logout.session.required: 'false'
      oauth2.device.authorization.grant.enabled: 'false'
      backchannel.logout.revoke.offline.tokens: 'false'
      saml.server.signature.keyinfo.ext: 'false'
      use.refresh.tokens: 'true'
      oidc.ciba.grant.enabled: 'false'
      backchannel.logout.session.required: 'true'
      client_credentials.use_refresh_token: 'false'
      require.pushed.authorization.requests: 'false'
      saml.client.signature: 'false'
      saml.allow.ecp.flow: 'false'
      id.token.as.detached.signature: 'false'
      saml.assertion.signature: 'false'
      client.secret.creation.time: '1705337498'
      saml.encrypt: 'false'
      saml.server.signature: 'false'
      exclude.session.state.from.auth.response: 'false'
      saml.artifact.binding: 'false'
      saml_force_name_id_format: 'false'
      acr.loa.map: '{}'
      tls.client.certificate.bound.access.tokens: 'false'
      saml.authnstatement: 'false'
      display.on.consent.screen: 'false'
      token.response.type.bearer.lower-case: 'false'
      saml.onetimeuse.condition: 'false'