apiVersion: builtin
kind: LabelTransformer
metadata:
  name: notImportantHere
labels:
  argocd.argoproj.io/managed-by: openshift-gitops
  test.label.io/test: test
fieldSpecs:
- kind: namespace
  path: metadata/labels
  create: true
---
apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: notImportantHere
annotations:
  argocd.argoproj.io/sync-wave: "0"
fieldSpecs:
- kind: namespace
  path: metadata/annotations
  create: true