kind: Secret
apiVersion: v1
metadata:
  name: keycloak-db-secret
  annotations:
    argocd.argoproj.io/sync-wave: "3"
stringData:
  POSTGRES_DATABASE: sso
  POSTGRES_EXTERNAL_ADDRESS: postgresql.sso-postgresql.svc.cluster.local
  POSTGRES_EXTERNAL_PORT: '5432'
  POSTGRES_PASSWORD: ErcvGUOoDSkxUSH4
  POSTGRES_SUPERUSER: true
  POSTGRES_USERNAME: userJWH
  SSLMODE: disable
type: Opaque
