kind: Secret
apiVersion: v1
metadata:
  name: credential-keycloak
  labels:
    app: keycloak
    keycloak: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "3"
stringData:
  ADMIN_PASSWORD: hoENPiNCH0bqZQ==
  ADMIN_USERNAME: admin
type: Opaque
